defmodule AdventOfCode2017Test do
  use ExUnit.Case
  doctest Day1.Captcha
  doctest Day2.Checksum
  doctest Day3.Grid
  doctest Day3.SumSpiral
  doctest Day4.Passphrase
  doctest Day4.AnagramPassphrase
  doctest Day5.Jump
  doctest Day6.MemoryReallocation
  doctest Day7.Tower
  doctest Day7.Program
  doctest Day8.Registry
  doctest Day8.Op
  doctest Day9.Stream
  doctest Day10.Knot
  doctest Day11.HexGrid
  doctest Day12.Graph
  doctest Day13.Firewall
  doctest Day14.Defragmentation
  doctest Day15.Generator
  doctest Day16.Dance
  doctest Day17.Buffer
  doctest Day18.Registry
  doctest Day18.Op
  doctest Day18.Duet
  doctest Day18.Program
  doctest Day19.Path
  doctest Day20.Particle
end
